### ISSUE TITLE
Remove Listen DisconnectDetector from epoll selected set when unregistering

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/dhtproto#114]
A `DisconnectDetector` instance is [newed on the stack](https://github.com/sociomantic-tsunami/dhtproto/blob/f2c1ccc72de8b15c684d362cf6138a919fa95f78/src/dhtproto/node/request/Listen.d#L71-L72), registered with epoll, then [unregistered](https://github.com/sociomantic-tsunami/dhtproto/blob/f2c1ccc72de8b15c684d362cf6138a919fa95f78/src/dhtproto/node/request/Listen.d#L94) when either an event occurs on the listened channel or `waitEvents` throws.

It is possible, in the case of an exception being thrown, that the `DisconnectDetector` has already fired in epoll, and is thus in the selected set being iterated over. As an exception will cause the `Listen.handleChannelRequest` method to exit, the `DisconnectDetector` will go out of scope. Thus, when the selected set iteration comes to handle it, a segfault will likely result.

https://github.com/sociomantic-tsunami/ocean/pull/458 contains a new feature that fixes this issue (optionally removing a client from the selected set when unregistering).

**Comment by nemanja-boric-sociomantic** [comment]
It looks like we'll have to do `static if (hasFeatures!("ocean", 3, 6))` to make this work, since dhtproto v13.x.x branch is tied to v3.3.x ocean. I think we'll have to mark this release `+breaking` since it will require updating to the latest patch release of v3.6.x ocean (since `hasFeatures` doesn't support checking for the patch release).

**Comment by gavin-norman-sociomantic** [comment]
Fixed by #115.
