### ISSUE TITLE
Slow neo Put performance reported

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/dhtproto#183]
An application that has been recently converted to use neo Put instead of legacy Put is reportedly performing noticeably worse than before.

The app works by assigning a large batch of Put requests once, periodically. In the legacy client, these would be pushed into the request queues (which were configured to be exceptionally large). A Task is associated with each Put request, leading to a large pool of tasks.

When using neo Put, the application's Task pool overflows.

The implication is that the time taken to handle a neo Put request is more than the time taken to handle a legacy Put request.

To be investigated.

**Comment by gavin-norman-sociomantic** [comment]
@joseph-wakeling-sociomantic could you confirm that my summary above is correct?

**Comment by joseph-wakeling-sociomantic** [comment]
Exceptionally large request queues only during local testing, where the total number of DHT nodes is small (1 or 2).  Queue size in production is much smaller (about 16 KiB), due to the larger numbers of DHT nodes, which creates greater parallelism in how the requests are dealt with.

**Comment by gavin-norman-sociomantic** [comment]
I've run the following, very simple test on a local DHT node:
1. Start a timer.
2. Assign 1,000 Put requests.
3. Wait for all requests to finish.
4. Measure the time taken by the batch and output it, along with the mean time per request in the batch.

Running this for legacy and neo Put requests, the neo Put requests seem slightly faster, on average, if anything.

**Comment by gavin-norman-sociomantic** [comment]
Ditto for batches of 4,000 Put requests.

**Comment by gavin-norman-sociomantic** [comment]
With batches of 4,000 records, the two protocols perform about the same.

**Comment by gavin-norman-sociomantic** [comment]
(Legacy tests performed with 10 connections per node and a 1Mb request queue per node.)

**Comment by joseph-wakeling-sociomantic** [comment]
Going by tests with the affected app, the task scheduler's number of worker fibers seems to be the key thing here: it was set high, and if it is reduced to 10 or 20 the time per put request is greatly reduced.

The likely reason is that with too high a number of worker fibers, it is hard to resume the send and receive fibers of the neo swarm client, hence data throughput is greatly reduced.

To reproduce I would suggest ensuring that:

* the number of worker fibers is high (in the region of 2000, 3000 or 4000)

* task queue size is high (in the app in question it's 30k)

* the legacy queue size is high (otherwise with legacy you'll hit its limits); I think something like 2 MiB or more

* the total number of tasks issued is more like 12,000 than 4,000, that number was distorted by the fact that in the app in question uses a taskpool and therefore recycles tasks quite efficiently when the number of worker fibers is high

**Comment by gavin-norman-sociomantic** [comment]
I've adapted my simple test to spawn a `Task` for each request. I can confirm that the number of worker fibers definitely impacts the speed at which neo requests complete:
* 5 worker fibers: average Put completion time ~85μs.
* 10 worker fibers: average Put completion time ~175μs.
* 20 worker fibers: average Put completion time ~400μs.
* 100 worker fibers: average Put completion time ~2,000μs.
* 1,000 worker fibers: average Put completion time ~18,000μs.

**Comment by joseph-wakeling-sociomantic** [comment]
For the record, I've seen no sign of this in production, so I think we can reasonably assume that this has an impact mostly in test setups where the number of DHT nodes (and hence connections, and hence send/receive fibers) is small relative to the number of worker fibers.

**Comment by gavin-norman-sociomantic** [comment]
Closing. Investigation showed that this isn't a problem specific to DHT Put. Moved description of core problem to swarm: https://github.com/sociomantic-tsunami/swarm/issues/376.
