### ISSUE TITLE
Partial handshake support: Mirror disk dump / load helper

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/dhtproto#82]
Some applications have code that does the following on a DHT channel:
* Uses the legacy `ChannelMirror` to mirror all records.
* Stores all received records in a cache or map in memory.
* Periodically / asynchronously writes the mirrored channel to disk.
* At shutdown, saves the mirrored channel to disk.
* At startup, loads the mirrored channel from disk then starts the channel mirror.

This sounds like useful behaviour for many apps and would be nice to have in a core library somewhere (using the neo Mirror request instead of `ChannelMirror`, of course). The question is how to break it down into one or more components that would sit nicely in the existing libraries.

**Comment by gavin-norman-sociomantic** [comment]
So this sounds like this could be broken down into 3 components, to me:
1. A DHT Mirror request. (That already encapsulates all the complexity that was managed by the legacy `ChannelMirror` class.)
2. An ocean cache enhanced with a periodic dump (probably somewhat abstract, not bound to any particular destination).
3. A means of asynchronous dumping. e.g. `SafeFork` or the [async disk I/O framework from the DLS node](https://github.com/sociomantic-tsunami/dlsnode/tree/master/src/dlsnode/util/aio).

**Comment by nemanja-boric-sociomantic** [comment]
Note that `SafeFork` is only half-safe: https://github.com/sociomantic-tsunami/ocean/issues/315

However, this can (and should and will) be fixed, and the good thing about forking is that it effectively does all critical section behaviour you need via copy-on-write mechanism. Because, in order to serialize the data structure, you need to make sure that changing it while dumping it to disk don't mess up with the data that already made it to the file, which is not a trivial problem for most data structures.

Alternative to all this is using disk persistent data structures, such as `BTree` and asynchronous dumping, but that sounds more like an enhancement to the existing cache/fork approach.

**Comment by gavin-norman-sociomantic** [comment]
I guess it's two different approaches:
1. Periodically fork and do a complete dump.
2. Write cache updates to disk as they come in (async I/O).

I'd be more inclined to favour the latter, but we can assess pros / cons.

**Comment by gavin-norman-sociomantic** [comment]
Alligator's implementation: https://github.com/sociomantic/alligator/blob/953425dcb1b56b711a8d8ceffcf96d3cea0e238c/src/alligator/cache/Cache.d.

**Comment by joseph-wakeling-sociomantic** [comment]
Note that this could be a problem where record deletion is concerned.

Legacy dhtproto mirrors do not handle record deletion, meaning that such records will stay in the local cache of any application.  If that's dumped to disk between runs, then they will _never_ lose those obsolete records.

**Comment by gavin-norman-sociomantic** [comment]
>Note that this could be a problem where record deletion is concerned.

Some applications already have their own implementation of a channel mirror disk cache. I asked the maintainers, and they said that it indeed does not handle removal of records (in the same way as the legacy channel mirror does not), but that, in practice, records are extremely seldom removed from the channels they're mirroring.

**Comment by gavin-norman-sociomantic** [comment]
>Some applications already have their own implementation of a channel mirror disk cache

Looking at the implementation of this, the really important parts are:
* A function to dump a map to disk.
* A means of handling errors while writing. (This implementation makes a backup of the old dump before writing the new one, and loads the backup if an error occurs while loading the dump. Another solution would be to use the approach used in the dhtnode: write dumps to a temp file and rename it on success.)
* A function to load a map from disk.

The file I/O uses the code in https://github.com/sociomantic-tsunami/ocean/blob/v4.x.x/src/ocean/util/container/map/utils/MapSerializer.d.

**Comment by gavin-norman-sociomantic** [comment]
There is also an extended class that adds:
* A function to asynchronously dump a map to disk (by forking).

I don't think this would be necessary for all applications, though.

**Comment by nemanja-boric-sociomantic** [comment]
As we had discussions if it's better to use forking approach or the writer thread and async IO, I'll just write down a small note here: I think forking is better suited to this use case because it enables `CoW` - which effectively freezes your map in time and you can dump it without worrying about the modifications (as long as you don't fork another time and write to the same file).

**Comment by gavin-norman-sociomantic** [comment]
Some more thoughts on this:
* It seems it's possible to use ocean's `MapSerializer` to [dump](https://github.com/sociomantic-tsunami/ocean/blob/v4.x.x/src/ocean/util/container/map/utils/MapSerializer.d#L739)/[load](https://github.com/sociomantic-tsunami/ocean/blob/v4.x.x/src/ocean/util/container/map/utils/MapSerializer.d#L910) arbitrary key-value data to/from disk.
* What's lacking is something that ties this together with `SafeFork` and a timer.
* I'm on the edge about whether we should try to package this all up with a data container and / or a channel mirror. Being able to set up all this stuff in a single object would be nice and convenient, but I'm not sure whether all our use cases can be that easily covered.

**Comment by joseph-wakeling-sociomantic** [comment]
> Being able to set up all this stuff in a single object would be nice and convenient, but I'm not sure whether all our use cases can be that easily covered.

Yup, I think it would be better to provide components that individual apps can use as appropriate to serve their needs.

Note that it might be useful to allow the serialization to be customizable.  If one is storing `Contiguous!(Something)` instances, or versioned structs, it would be nice to be able to use the contiguous serialization functionality of ocean, rather than a generic "map serialization" mechanism.  Think e.g. if one is caching versioned structs, and then the struct version changes between app deployments -- one wants to be able to read and convert the serialized data.  A generic mechanism that doesn't care about the type of values will not support this.

A consideration: if all one wants to do is have an on-disk copy of the channel, one does not necessarily need to dump data from the same local cache that one uses internally in the app.  One could just pass on the _serialized_ data as it is received by the mirror, to some other piece of functionality that takes care of ensuring it is written to disk appropriately.

**Comment by Geod24** [comment]
> Note that it might be useful to allow the serialization to be customizable.

If the [imports](https://github.com/sociomantic-tsunami/ocean/blob/9050f79a37bcf55575f2a97f060c4e71ceeb07c8/src/ocean/util/container/map/utils/MapSerializer.d#L47-L49) at the top of the module didn't tip you off, [this might](https://github.com/sociomantic-tsunami/ocean/blob/9050f79a37bcf55575f2a97f060c4e71ceeb07c8/src/ocean/util/container/map/utils/MapSerializer.d#L1125-L1153). The only usability issue of this module I know of (besides its code needing a good cleanup) is that you can only convert versions up, not down, which make rollback complicated ATM.

> One could just pass on the serialized data as it is received by the mirror

As mentioned by @gavin-norman-sociomantic :

> What's lacking is something that ties this together with `SafeFork` and a timer.

So the serialization itself is not an issue.
Using the mirror you would not likely want to go through the hassle of supporting mirroring request updating your cache, so the cache updates would have to be tied to a multiple of the `GetAll` timer.

**Comment by gavin-norman-sociomantic** [comment]
Maybe a crazy idea: it sounds to me like what we really need is support _in the app base class_ for loading a file and dumping it asynchronously, optionally on a timer. We already have app-level timers built into the app base class.

**Comment by joseph-wakeling-sociomantic** [comment]
> If the imports at the top of the module didn't tip you off, this might.

I hadn't actually looked at the `MapSerializer` code yet; thanks for the clarifications.  Do I understand right that this implementation makes a strong assumption that the map values are versioned structs?  No alternatives?

> The only usability issue of this module I know of (besides its code needing a good cleanup) is that you can only convert versions up, not down, which make rollback complicated ATM.

Another is that people might be storing _unversioned_ structs.

I'm not sure we should be placing too-strong assumptions around the nature of what is being cached and how to convert it to/from the data being dumped/loaded to disk.

**Comment by joseph-wakeling-sociomantic** [comment]
@gavin-norman-sociomantic I don't quite follow the reasoning behind why coupling with the app base class would be a good idea (except perhaps for ease of implementation)?

**Comment by gavin-norman-sociomantic** [comment]
I'm just looking at things as abstractly as possible. I think we actually already have all of the required components for this. So I was thinking: what stops people from using these components in their apps? 1. Lack of knowledge that these things exist (and how to use them together); 2. Lack of integration into code that everyone uses.

This second point is what led me to the app base class. It seems like the most obvious place to put a generic "load file from disk / periodically dump it to disk" framework.

**Comment by Geod24** [comment]
> Do I understand right that this implementation makes a strong assumption that the map values are versioned structs? 

No. If you're interested, the documentation is pretty extensive about what is supported.

**Comment by joseph-wakeling-sociomantic** [comment]
> No. If you're interested, the documentation is pretty extensive about what is supported.

I'd read the documentation, and didn't find it entirely clear; the top-level module doc seemed straightforward enough, but reading further down into details made me uncertain about what was supported (or not), and how.

In particular: all the options referred to in the top-level doc seemed to refer to stuff that ultimately depended on `MapSerializer`, and the docs of `MapSerializer` were not clear about what (if anything) would happen for arbitrary value types, while being _very_ detailed about versioned structs and associated requirements.

That caused the doubts about whether anything other than versioned structs were really supported.

**Comment by gavin-norman-sociomantic** [comment]
Yeah, I definitely think this module could be cleaned up. As Mathias said.

**Comment by joseph-wakeling-sociomantic** [comment]
@gavin-norman-sociomantic about the more abstract issue: I think it's straightforwardly not knowing about the existing ocean features, because it's only with partial DHT handshake support that many apps have acquired the use-case.

My own assumption was probably something along the lines of, "If there was already a reasonable general-purpose solution, someone would have raised it the moment we identified the problem".

On coupling to the app: it feels like:

* if workable, it could be useful to have some kind of general-purpose task that runs things using `SafeFork`, that could be used arbitrarily ("just use the forking task...")

* it _might_ be useful to have an easy way to define custom timer-based app plugins (if it isn't already easy), but that doesn't really seem essential to this use-case

* depending on the nature and size of the data being cached, it might be preferable to dump data not based on a timer but based on (amount of?) change (e.g. a cache might compare a newly-received value to the existing one, and dump on a record-by-record basis if any change occurs; this would only be slow if the rate of change is frequent)

* more generally: how to _schedule_ a data dump (whether of lots of data or incremental pieces) should be up to the app, it's how to dump data without blocking the app that is the major concern

**Comment by gavin-norman-sociomantic** [comment]
>if workable, it could be useful to have some kind of general-purpose task that runs things using SafeFork, that could be used arbitrarily ("just use the forking task...")

True, it needn't be tied to file dumping.

>it might be useful to have an easy way to define custom timer-based app plugins (if it isn't already easy)

Yep, we already have support for app-level timers.

**Comment by gavin-norman-sociomantic** [comment]
It's sounding more and more like all we need here is a good usage example.

**Comment by joseph-wakeling-sociomantic** [comment]
> It's sounding more and more like all we need here is a good usage example.

Yes, or maybe a collection of different usage examples with different priorities in mind.

**Comment by gavin-norman-sociomantic** [comment]
Rough implementation: https://github.com/sociomantic-tsunami/dhtproto/pull/162.
